### ISSUE TITLE
Consider contributing this back to use-package?

### ISSUE THREAD

**Issue by phil-s** [waymondo/use-package-ensure-system-package#1]
If you haven't done so already, please consider having a conversation about whether this feature could be merged into `use-package` itself.

`use-package` is going to become standard Emacs functionality, and your library sounds like a really nice enhancement which could be great to also have available by default.

**Comment by waymondo** [comment]
Cool, thanks for note. I'll open a issue and see what John thinks. I offered to add `:chords` keyword support for `key-chord` to `use-package` while back but he encouraged me to go the plugin route, which was introduced in 2.0.

**Comment by phil-s** [comment]
Nice one!
