### ISSUE TITLE
Installing things without binaries

### ISSUE THREAD

**Issue by justinabrahms** [waymondo/use-package-ensure-system-package#2]
I want to `:ensure-system-package` some libraries like `libpng`, but I don't want it to re-install each time (which I believe is how things work under the hood). Do you have guidance here?

**Comment by waymondo** [comment]
This package lives in the `use-package` repo for now and the version there contains the feature. You can see the solution towards the end of this section: https://github.com/jwiegley/use-package#use-package-ensure-system-package.

Essentially, you can check for the presence of a known file or executable path of the installed package. If it exists, the install command will be bypassed.
